---
version: "2"
plugins:
  tslint:
    enabled: true
    config: tslint.json
  nodesecurity:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - typescript
checks:
  method-complexity:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 50
exclude_patterns:
- "assets/"
