---
plugins:
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - BUG
      - TODO
      - REFACTOR
  tslint:
    enabled: true
    channel: beta
    config: tslint.json
  duplication:
    enabled: true
    exclude_paths:
    - config
    config:
      languages:
      - javascript
      - typescript

ratings:
  paths:
  - src/**/*
  - config/**/*
  - "**.ts"
  - "**.js"
exclude_paths:
- dist
