sudo: required
language: node_js
node_js:
- 10.3.0
cache:
  directories:
  - node_modules
code_climate:
  repo_token:
    secure: goxMom8RmEZNErkniM/kBg0xxu/xEFlXfEkn7wR4Jmpfx+9iFDWuqTz6dh9p0jdwDNoKRcav6O5zH+ssMXmVJAVT5BbCteq8+rfI5l15E8fdB1lcAD0wSBav6pPaur3pyci+NaFI4T1l8UUgeyPCq84O9jzO7uXHsOttlpNGKuO7F4FEg/4ZQNd4sTRyxvONd3rHcQtR2SevzCNjq++bLKa8M+ph0c2BNcCsIP99B0CTBaIGPXCmbRNzKG9FPfrlk99MXiKajq0hrExk3PxyaMwLWFQTsXfg/Ld2FRWvAGxq31h3fp7Ak+6BgGUL2jZtNt7MOSXeT7at7UcjmCeoq2hAD4bM30B7Um2snxaDfg1rEjcM3cpFitX8yEGai+yl4POlBiix28ONiH+JBKUsmUI6xq83rm2JsyyqHM5O34sI/LpioydJsT7wT3P6OfDmL54JFe5Y3vMT4AAHqwY9wkHuM4xC5XDZLSIoLSzdZwxh/HSZOn3W+bS01vMvtE8drye5N9CnHJoEPLsOFrNsUHeYuxgsE+sBvy8Z1YEUbR1hArHiMNASSCzo6+SM1nwg0+sx3eowMs9uw/1vMwrGVZB//4qBLpa41wi3CYv3+MvnSYvEBkfiBBShuM6Kf4bpuSfN/Lg3bh/0zLxiXqfr7atLiD7Y1+0t0a1jUN/DzJ8=
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
    - google-chrome-beta
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm install -g @angular/cli
- npm install codeclimate-test-reporter
script:
- ng lint
- npm run test-with-coverage
- ng e2e
- npm run build-with-timestamp
after_script:
- codeclimate-test-reporter < ./coverage/lcov.info
deploy:
  skip_cleanup: true
  provider: firebase
  on:
    branch: master
  token:
    secure: m2nW67b9l0E9kHefKU4dXMsdyiRJEvDMkW3VEcRRveg6nveOAxbZaYzryZ3Qj3TSPqQtApwa8PlxzrKMKY7//Om/JnPfOQ49w15L+eax/zKgfhFdRAKvzddXy+0AhBcSlWZTTtIbbk/I384ts5/bpluSNy5VkRd8Z66q4Vk05TMN0qQZDvBfnODEU2L6cKmLO3Gii248lbhPiraAtNZEFoJUOLNTF90W02fDZAZ8b3clElgYQ+SNfBH540YtswXiNvb5kIarxYEBhOfWiYXXbR4gFGjTh/fwAUrCgNF0v43X769ACy1Mfm5B5L9qx0mpCPYW5WNGmy3GJtxa8raz1T8Sbm0QIhFTimTr990t7eFQ/XooXvMcOH45Wfl02kDQ1oyrvHM6BucuR7LZ44kciGfXvSZAuBs3UlNTXnd5Z+Dve1d6AIVgDmgEzjkLq0YDqbXHY7xuJt/saAkCtAujCzUgNUrxf/ktDLq0uQyFl1ATlWJR7FNeQukjuzQD4Z1sfqcJOdEshQTKS+F54y3Z9xtgFpzmLUtRYXxPU6G0iSh+rsp/mrlCYdQyX7lGDhSAbgR9VtUupy55ZljL8wKqKHuvHjucRoqT+WfYs78Ex6/CS/zxQ7F/24Tbsn1O3zoQdtud327Qf+DpFpbofYee0tBFZL/U8r8AWenVcLHF/1E=

