sudo: required
language: node_js
node_js:
  - '10.3.0'

cache:
  directories:
    - "node_modules"

before_script:
  - npm install -g @angular/cli
  - npm ci
  - ng build

script:
  - ng test --watch=false
  - ng e2e
